version: '3'
services:

  backend:
    container_name: laravel-docker
    build:
      context: .
    volumes:
      - /home/ubuntu/projects/laravel-docker:/var/www/html  
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_DATABASE: auth_app
      DB_TEST: vikash
    depends_on:
      - mysql

  mysql:
     image: mysql:5.7
     environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth_app
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: 123456
     ports:
       - 3306:3306
     volumes:
      - mysql-data:/var/lib/mysql  # Mount the volume for MySQL data storage

volumes:
  mysql-data:

